services:
  # Este corre mosquito
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"    # MQTT
      - "8883:8883"    # MQTTS (secure)
      - "9001:9001"    # WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  db:
      image: postgres:latest
      container_name: postgres_db
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: nombre_de_tu_bd
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: