services:
  # Este corre mosquito
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"    # MQTT
      - "8883:8883"    # MQTTS (secure)
      - "9001:9001"    # WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  db:
      image: postgres:latest
      container_name: postgres_db
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: epicmomo
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
      - iot_net
  set_up_db:
    build: set_up_db/.
    depends_on:
      - db
    networks:
      - iot_net
  dashboard:
    build: streamlit/.
    container_name: streamlit_iot
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - db
    networks:
      - iot_net
networks:
  iot_net:
    driver: bridge
volumes:
  pgdata: